--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VennDev/VItemsAPI
build-by-default: true
branches:
- main
projects:
  VItemsAPI:
    path: ""
    libs:
      - src: VennDev/LibVapmPMMP/LibVapmPMMP
        version: ^2.3.5
        branch: "main"
...
